# This is a basic workflow to help you get started with Actions

name: Build tModLoader

# Controls when the action will run. 
on:
  push:
    branches: [github-actions-experiments]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build script
        shell: bash
        run: |
          echo Downloading Terraraia Server zip
          curl -s -L http://terraria.org/server/terraria-server-1353.zip -o terrariaserver.zip
          unzip -q terrariaserver.zip
          echo Make fake Terraria.exe (Temp)
          cp .\1354\Windows\TerrariaServer.exe .\1354\Windows\Terraria.exe
          echo ls -l is:
          ls -l
          echo Installing XNA
          curl -s -L https://download.microsoft.com/download/5/3/A/53A804C8-EC78-43CD-A0F0-2FB4D45603D3/xnafx40_redist.msi -O
          msiexec //i xnafx40_redist.msi //quiet
          echo XNA Installed
          echo Running setupcommandline.bat
          setupcommandline.bat
          echo Done
          echo Building Windows Client exe 
          C:/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe .\solutions\tModLoader.sln /restore /p:Configuration=WindowsRelease
          echo Done.
          
      - uses: actions/upload-artifact@v2
        with:
          name: Windows Release exe
          path: ./src/tModLoader/bin/WindowsRelease/net45/Terraria.exe
          
