# This is a basic workflow to help you get started with Actions

name: Build tModLoader

# Controls when the action will run. 
on:
  push:
    branches: [github-actions-experiments]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Build script
        run: |
          echo Downloading Terraraia Server zip
          curl -s -L http://terraria.org/server/terraria-server-1353.zip -o terrariaserver.zip
          unzip -q terrariaserver.zip
          echo ls -l is:
          ls -l
          
      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: Windows Release exe
      #    path: ./src/tModLoader/bin/WindowsRelease/net45/Terraria.exe
          
